# master.yml
- hosts: all
  become: true
  vars:
    kubernetes_version: "1.21.0-00"
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add kubernetes apt repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install kubeadm, kubelet and kubectl
      apt:
        name:
          - kubelet={{kubernetes_version}}
          - kubeadm={{kubernetes_version}}
          - kubectl={{kubernetes_version}}
        state: present

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Enable kernel modules
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        sysctl_file: /etc/sysctl.d/99-kubernetes-{{ item }}.conf
        reload: yes
      with_items:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward

    - name: Configure firewall rules
      ufw:
        rule: allow
        port: "{{ item }}"
      with_items:
        - 6443
        - 2379:2380
        - 10250:10252
        - 30000:32767

    - name: Initialize kubernetes cluster
      command: kubeadm init --pod-network-cidr=192.168.0.0/24
      register: kubeadm_init
      changed_when: false

    - name: Copy kubernetes config to user directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: true
        owner: ubuntu
        group: ubuntu

    - name: Install flannel network plugin
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    - name: Get join command for worker nodes
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Save join command to file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /home/ubuntu/join-command.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'